### ISSUE TITLE
How can I use it before to show RecyclerView?

### ISSUE THREAD

**Issue by pengkshu** [medyo/dynamicbox#13]
In a activity, I have a RecyclerView and other view,I want to show the RecyclerView after load all data.How should I use?I have some confusion

**Comment by medyo** [comment]
Hi @pengkshu 
RecyclerView will be supported in the coming version, it should be published today.
I'll update this answer once published

**Comment by pengkshu** [comment]
thinks,I think this version also support RecyclerView.I solved my problem.thinks so much

**Comment by medyo** [comment]
If you wrap it on a supported View it'll work, however using it as directly as parameter will throw an error.
